"""
Compile and run BatchApplyTemplates MQL5 script using MetaEditor.
MetaEditor64.exe can compile MQL5 files from command line.
Then we run the compiled script from MT5.
"""
import os, time, ctypes, subprocess, glob

APPDATA = os.environ.get('APPDATA', '')
MT5_DIR = r'C:\Program Files\MetaTrader 5'
MT5_EXE = os.path.join(MT5_DIR, 'terminal64.exe')
ME_EXE = os.path.join(MT5_DIR, 'MetaEditor64.exe')
MT5_DATA = os.path.join(APPDATA, 'MetaQuotes', 'Terminal',
                        'D0E8209F77C8CF37AD8BF550E51FF075')
SCRIPTS_DIR = os.path.join(MT5_DATA, 'MQL5', 'Scripts')
TPL_DIR = os.path.join(MT5_DATA, 'Profiles', 'Templates')
COMMON_FILES = os.path.join(APPDATA, 'MetaQuotes', 'Terminal', 'Common', 'Files')
LOG_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'auto_attach_log.txt')
SYSTEM_EAS = {'TestBlank.ex5', 'TemplateLoader.ex5', 'AgentHelper.ex5'}

# First, generate templates for ALL EAs
print("=" * 60)
print("  COMPILE & RUN BATCH TEMPLATE SCRIPT")
print("=" * 60)

# Step 1: Update the BatchApplyTemplates.mq5 to include ALL EAs
mq5_path = os.path.join(SCRIPTS_DIR, 'BatchApplyTemplates.mq5')
print(f"\n📋 Source: {mq5_path}")

# Read current template list
with open(mq5_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Get all EA names
all_ex5 = [f for f in os.listdir(os.path.join(MT5_DATA, 'MQL5', 'Experts')) if f.endswith('.ex5')]
ea_names = sorted([f[:-4] for f in all_ex5 if os.path.basename(f) not in {'TestBlank.ex5', 'TemplateLoader.ex5', 'AgentHelper.ex5'}])
print(f"📋 {len(ea_names)} EAs to include")

# Generate template list for MQL5
tpl_entries = []
for ea in ea_names:
    tpl_name = f"{ea}_EURUSD_H1.tpl"
    tpl_entries.append(f'      "{tpl_name}",')
tpl_list = '\n'.join(tpl_entries)

# Write updated MQL5 file
updated = f'''//+------------------------------------------------------------------+
//| BatchApplyTemplates.mq5 - Generated by Hermes Agent             |
//| Applies templates for all EAs                                   |
//+------------------------------------------------------------------+
void OnStart()
{{
   string templates[] = {{
{tpl_list}
   }};
   
   for(int i = 0; i < ArraySize(templates); i++)
   {{
      string tpl = templates[i];
      string ea_name = StringSubstr(tpl, 0, StringFind(tpl, "_"));
      
      Print("Applying template: ", tpl);
      long chart_id = ChartOpen("EURUSD", PERIOD_H1);
      if(chart_id <= 0)
      {{
         Print("Failed to open chart for ", ea_name);
         continue;
      }}
      
      if(ChartApplyTemplate(chart_id, tpl))
      {{
         Print("SUCCESS: ", ea_name, " deployed to EURUSD H1");
      }}
      else
      {{
         Print("FAILED: ", ea_name, " error=", GetLastError());
      }}
      ChartRedraw(chart_id);
      Sleep(100);
   }}
   Print("Batch complete");
}}
//+------------------------------------------------------------------+
'''

with open(mq5_path, 'w', encoding='utf-8') as f:
    f.write(updated)
print("✅ MQL5 file updated")

# Step 2: Compile using MetaEditor64.exe
print("\n📋 Compiling...")
compile_cmd = [ME_EXE, '/compile:' + mq5_path, '/s']
print(f"  Command: {' '.join(compile_cmd)}")
result = subprocess.run(compile_cmd, capture_output=True, timeout=30)
print(f"  Result: {result.returncode}")
stdout = result.stdout.decode('utf-8', errors='replace')
stderr = result.stderr.decode('utf-8', errors='replace')
if stdout:
    print(f"  stdout: {stdout[:500]}")
if stderr:
    print(f"  stderr: {stderr[:500]}")

# Check if .ex5 was created/updated
ex5_path = os.path.join(SCRIPTS_DIR, 'BatchApplyTemplates.ex5')
if os.path.exists(ex5_path):
    mtime = os.path.getmtime(ex5_path)
    age = time.time() - mtime
    print(f"✅ Compiled: {ex5_path} ({age:.0f}s old)")
else:
    print("❌ Compilation failed - no .ex5 output")
    # Try alternative compile syntax
    print("\n  Trying alternative compile syntax...")
    compile_cmd2 = [ME_EXE, '/compile', mq5_path, '/log']
    result2 = subprocess.run(compile_cmd2, capture_output=True, timeout=30)
    print(f"  Result: {result2.returncode}")
    print(f"  stdout: {result2.stdout.decode('utf-8', errors='replace')[:500]}")
    print(f"  stderr: {result2.stderr.decode('utf-8', errors='replace')[:500]}")
